version: '3'
services:
  blockchain:
    build: ./blockchain
    ports:
      - "8545:8545"
    volumes:
      - blockchain_data:/app/build
      - shared_abi:/shared

  backend:
    build: ./backend
    expose:
      - "5000"
    depends_on:
      - blockchain
    volumes:
      - shared_abi:/shared
    environment:
      - WEB3_PROVIDER=http://blockchain:8545

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    command: npm start

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  blockchain_data:
  shared_abi:
  frontend_build: