version: '3'
services:
  blockchain:
    build: ./blockchain
    ports:
      - "8545:8545"
    volumes:
      - blockchain_data:/app/build
      - shared_abi:/shared

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - blockchain
    volumes:
      - shared_abi:/shared
    environment:
      - WEB3_PROVIDER=http://blockchain:8545

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  blockchain_data:
  shared_abi: